Add FromStr impl for operands
gfx-rs/rspirv pull request #171
Opened 2020-11-12 16:44 UTC by khyperia

This would be a pain to implement all the boilerplate for outside of rspirv, so throwing it in here for our use case in rust-gpu.

Note that this does _not_ implement FromStr for `bitflags!` operands, but implementing FromStr for those becomes a bit opinionated - do you create a list of values? how do you separate each individual value? so it's not really possible to impl it in an unopinionated way (and besides, there's not many bitflags, it's easy enough for users to implement their own FromStr).

2020-11-12 16:47 UTC, MarijnS95 commented on autogen/header.rs
> +            from_str_impl.push(quote! { #name_str => Ok(#kind::#name), });
Could this be

```suggestion
            from_str_impl.push(quote! { #name_str => Ok(Self::#name), });
```

To save quite a bunch of characters on every line?

2020-11-12 16:56 UTC, MarijnS95 approved these changes
Awesome! Approval from me, if counts at all :sweat_smile: 

It's sad there's no `#[derive(FromStr)]` though, these are about ~800 extra lines for strings that appear identical to their `enum` variant yet could be generated at compile-time instead of checked in. The perks of auto-generated files :grin:

2020-11-13 11:48 UTC, Jasper-Bekkers requested changes

2020-11-13 11:48 UTC, Jasper-Bekkers commented on autogen/header.rs
> +            from_str_impl.push(quote! { #name_str => Ok(Self::#name), });
I think the aliases should probably also appear. Right now `ClosestHitKHR` isn't recognised but `ClosestHitNV` is for example, however the new way forward it through the KHR extension.

2020-11-13 12:10 UTC, Jasper-Bekkers approved these changes

2020-11-13 12:13 UTC, merged